# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc3a179fb7833c7323eb107e8fc4d6f5f83c3ce72bf79eea38fc5627a8014a53ebd25ac2a644941dfcf7fb58b723ee01f471055b2247c952d7f235d525d98036

test:
  secret_key_base: 038c89b476864fecab8c711f988199459604e8106c094906df403d26db6781dea584bb3be12a3d660b19be710df2ad6d8bc56f174d57976092dd4d610a36a0f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
